---
- name: Validate NTLM to Windows host
  hosts: win
  gather_facts: no

  tasks:
    - name: Assert we are using NTLM
      ansible.builtin.assert:
        that: ansible_winrm_transport | lower == 'ntlm'
        fail_msg: "Not using NTLM (ansible_winrm_transport={{ ansible_winrm_transport }})"
        success_msg: "NTLM transport confirmed."

    - name: Basic ping
      ansible.windows.win_ping:

    - name: Run 'hostname' via WinRM
      ansible.windows.win_command: hostname

    - name: Show server date via PowerShell
      ansible.windows.win_shell: Get-Date

    - name: Read WinRM auth config (proof from the host)
      ansible.windows.win_shell: "(Get-WSManInstance -ResourceURI winrm/config/service).Auth | ConvertTo-Json"
      register: auth_cfg

    - name: Print auth settings
      ansible.builtin.debug:
        var: auth_cfg.stdout
